apiVersion: apps/v1
kind: Deployment
metadata:
  name: pki-injector-webhook-svc
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
  labels:
    app: pki-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pki-injector
  template:
    metadata:
      labels:
        app: pki-injector
    spec:
      tolerations:
        - key: polyglot.systems/lifespan-remaining
          operator: Exists
          effect: NoSchedule
      containers:
        - name: pki-injector
          image: quay.io/kenmoini/ocp-mutating-webhook-pod-mounter:latest
          imagePullPolicy: Always
          args:
          - -sidecarCfgFile=/etc/webhook/config/config.yaml
          - -tlsCertFile=/etc/webhook/certs/tls.crt
          - -tlsKeyFile=/etc/webhook/certs/tls.key
          - 2>&1
          env:
          - name: TLS
            value: "true"
          - name: LOG_LEVEL
            value: "trace"
          - name: LOG_JSON
            value: "false"
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
          - name: webhook-config
            mountPath: /etc/webhook/config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
      - name: webhook-certs
        secret:
          secretName: service-serving-cert
      - name: webhook-config
        configMap:
          name: pki-injector-webhook-configmap