apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    app: sidecar-injector
webhooks:
- name: sidecar-injector.kenmoini.me
  clientConfig:
    service:
      name: sidecar-injector-webhook-svc
      namespace: sidecar-injector
      path: "/mutate"
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
  sideEffects: None
  admissionReviewVersions: ["v1"]