apiVersion: v1
kind: Service
metadata:
  name: pki-injector-webhook-svc
  labels:
    app: pki-injector
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
    service.beta.openshift.io/serving-cert-secret-name: service-serving-cert
spec:
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: pki-injector