apiVersion: v1
kind: Service
metadata:
  name: sidecar-injector-webhook-svc
  labels:
    app: sidecar-injector
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: service-serving-cert
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: sidecar-injector