apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pki-injector.polyglot.systems
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
    kubectl.kubernetes.io/last-applied-configuration: ""
  labels:
    app: pki-injector
webhooks:
  - name: pki-injector.polyglot.systems
    clientConfig:
      service:
        name: pki-injector-webhook-svc
        namespace: pki-injector
        path: "/validate-pods"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
        scope: "*"
    namespaceSelector:
      matchLabels:
        sidecar-injection: enabled
    sideEffects: None
    admissionReviewVersions: ["v1"]